version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: caminhoDev-api
    restart: always
    ports:
      - '3333:3333'
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - caminhoDev_network

networks:
  caminhoDev_network:
    driver: bridge
