version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: caminhoDev-api
    restart: always
    ports:
      - '3333:3333'
      - '5555:5555'
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - caminhoDev_network
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:docker@postgres:5432/caminhodev?schema=public

  postgres:
    image: postgres:latest
    container_name: caminhoDev-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=caminhodev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma:/docker-entrypoint-initdb.d
    networks:
      - caminhoDev_network

networks:
  caminhoDev_network:
    driver: bridge

volumes:
  postgres_data:
